password_encryption_secret_key: <%= ENV['PASSWORD_ENCRYPTION_SECRET_KEY'] || '1bb3d19f484c4e3b905896a1fa773afd' %>

omniauth:
  provider: <%= ENV['OMNIAUTH_PROVIDER'] || 'github' %>
  args: <%= eval(ENV['OMNIAUTH_ARGS'] || '[]') %>
