require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CooksController do

  # This should return the minimal set of attributes required to create a valid
  # Cook. As you add validations to Cook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "host" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cooks as @cooks" do
      cook = Cook.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cooks).should eq([cook])
    end
  end

  describe "GET show" do
    it "assigns the requested cook as @cook" do
      cook = Cook.create! valid_attributes
      get :show, {:id => cook.to_param}, valid_session
      assigns(:cook).should eq(cook)
    end
  end

  describe "GET new" do
    it "assigns a new cook as @cook" do
      get :new, {}, valid_session
      assigns(:cook).should be_a_new(Cook)
    end
  end

  describe "GET edit" do
    it "assigns the requested cook as @cook" do
      cook = Cook.create! valid_attributes
      get :edit, {:id => cook.to_param}, valid_session
      assigns(:cook).should eq(cook)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cook" do
        expect {
          post :create, {:cook => valid_attributes}, valid_session
        }.to change(Cook, :count).by(1)
      end

      it "assigns a newly created cook as @cook" do
        post :create, {:cook => valid_attributes}, valid_session
        assigns(:cook).should be_a(Cook)
        assigns(:cook).should be_persisted
      end

      it "redirects to the created cook" do
        post :create, {:cook => valid_attributes}, valid_session
        response.should redirect_to(Cook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cook as @cook" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cook.any_instance.stub(:save).and_return(false)
        post :create, {:cook => { "host" => "invalid value" }}, valid_session
        assigns(:cook).should be_a_new(Cook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cook.any_instance.stub(:save).and_return(false)
        post :create, {:cook => { "host" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cook" do
        cook = Cook.create! valid_attributes
        # Assuming there are no other cooks in the database, this
        # specifies that the Cook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cook.any_instance.should_receive(:update).with({ "host" => "" })
        put :update, {:id => cook.to_param, :cook => { "host" => "" }}, valid_session
      end

      it "assigns the requested cook as @cook" do
        cook = Cook.create! valid_attributes
        put :update, {:id => cook.to_param, :cook => valid_attributes}, valid_session
        assigns(:cook).should eq(cook)
      end

      it "redirects to the cook" do
        cook = Cook.create! valid_attributes
        put :update, {:id => cook.to_param, :cook => valid_attributes}, valid_session
        response.should redirect_to(cook)
      end
    end

    describe "with invalid params" do
      it "assigns the cook as @cook" do
        cook = Cook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cook.any_instance.stub(:save).and_return(false)
        put :update, {:id => cook.to_param, :cook => { "host" => "invalid value" }}, valid_session
        assigns(:cook).should eq(cook)
      end

      it "re-renders the 'edit' template" do
        cook = Cook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cook.any_instance.stub(:save).and_return(false)
        put :update, {:id => cook.to_param, :cook => { "host" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cook" do
      cook = Cook.create! valid_attributes
      expect {
        delete :destroy, {:id => cook.to_param}, valid_session
      }.to change(Cook, :count).by(-1)
    end

    it "redirects to the cooks list" do
      cook = Cook.create! valid_attributes
      delete :destroy, {:id => cook.to_param}, valid_session
      response.should redirect_to(cooks_url)
    end
  end

end
